-- AlterEnum
ALTER TYPE "EmailKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_PAUSED';
ALTER TYPE "EmailKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_RESUMED';
ALTER TYPE "EmailKind" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_EXPIRED';
